### ISSUE TITLE
Pindahkan beberapa setting di Administration ke dalam Conference

### ISSUE THREAD

**Issue by faisalwahyudi10** [OpenSynergic/leconfe#249]
Setting format tanggal dan jam saat ini masih berada pada setting administration, pindahkan setting ini ke dalam masing-masing conference

![image](https://github.com/OpenSynergic/leconfe/assets/121210620/db85e9c0-9795-4665-b65b-281c97b6bb26)

**Comment by rahmanramsi** [comment]
Access options : 
![CleanShot 2024-05-18 at 15 08 39](https://github.com/OpenSynergic/leconfe/assets/48276043/c97c3bec-7b17-4186-8c96-32e57f827a55)
