### ISSUE TITLE
(Bug) Halaman Presenters bisa diakses oleh role lain 

### ISSUE THREAD

**Issue by rahmanramsi** [OpenSynergic/leconfe#252]
Diakses oleh user yg mendaftar sebagai Author

![CleanShot 2024-05-18 at 11 19 18](https://github.com/OpenSynergic/leconfe/assets/48276043/2bda1939-fed6-4d71-8fc8-6ef5c2e21ce0)

**Comment by faisalwahyudi10** [comment]
Untuk presenter ini role apa saja yang bisa mengakses nya bang?

![image](https://github.com/OpenSynergic/leconfe/assets/121210620/055914ee-21dc-4805-866e-c1ebee869adf)

**Comment by faisalwahyudi10** [comment]
- Author dan Editor dapat Set Decision Presenter
- Presenter dapat di approve di submission
- Kalau prensenter belum di approve terdapat peringatan
