### ISSUE TITLE
Registration Policy

### ISSUE THREAD

**Issue by gokilalma** [OpenSynergic/leconfe#360]
1.Style dari Registration Policy perlu di rapikan, karena style pada halaman backend dan frontend menampilkan hasil yg berbeda

![image](https://github.com/user-attachments/assets/d20e9ae7-07fb-421b-8270-7bb6272c9554)

2. Data Registration Policy tidak tampil ketika status pembayaran menjadi Paid, lebih baiknya policy ini tetap di pertahankan di bawah status pembayarannya

![image](https://github.com/user-attachments/assets/73721b4a-1a6b-41d8-9d82-e84c45e0fa9e)

![image](https://github.com/user-attachments/assets/288f1ef2-0e31-4d2f-8010-43a5ccbb4aad)

**Comment by SalimQS** [comment]
Preview: 
![ss leconfe 2](https://github.com/user-attachments/assets/2860afd7-3e75-43f8-a425-9ae14c69f014)

Setting:
![image](https://github.com/user-attachments/assets/c10f592b-10aa-4254-ae54-43bb66f075dc)

**Comment by SalimQS** [comment]
Preview: 
![ss leconfe 2](https://github.com/user-attachments/assets/2860afd7-3e75-43f8-a425-9ae14c69f014)

Setting:
![image](https://github.com/user-attachments/assets/c10f592b-10aa-4254-ae54-43bb66f075dc)
