### ISSUE TITLE
Add feature for leconfe, req by UMS

### ISSUE THREAD

**Issue by gokilalma** [OpenSynergic/leconfe#427]
1. Added option to disable register new users as Reviewers
![image](https://github.com/user-attachments/assets/c37c585c-33f2-47bd-a822-050c277a5fcb)

2. Added "public name" data entry for user, speaker, and committee data.
![image](https://github.com/user-attachments/assets/0cdbe0b6-18ed-40b9-8ed9-95669706c7da)

**Comment by rahmanramsi** [comment]
Done #430 and #429
